ID_GRAPHS_CONFIG = dict(
	FIGURE_GRID_X_ELEMS = 4,
	FIGURE_GRID_Y_ELEMS = 3,
	FIGURE_HEIGHT = 30,
	FIGURE_WIDTH = 40,
	SUPTITLE_FONT_SIZE = 30,
	FIGURES_FONT_SIZE = 22,
	TOP_MARGIN = 0.95
)
DEFAULT_PARAMS = dict(
	OCCUPANCY_RATE = 0.5,
	HASH_NUM = 6,
	WINDOW_SIZE = 19
)